global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8405']

  - job_name: 'cadvisor'
    static_configs:
       - targets: ['cadvisor:8080']
