apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 14268
          protocol: TCP
        - containerPort: 9411
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: udp-query
      protocol: UDP
      port: 5775
      targetPort: 5775
    - name: udp-sampling
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: udp-zipkin
      protocol: UDP
      port: 6832
      targetPort: 6832
    - name: http-query
      protocol: TCP
      port: 5778
      targetPort: 5778
    - name: http-web
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: http-jaeger-tracing
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: http-collector
      protocol: TCP
      port: 9411
      targetPort: 9411
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ingress
  labels:
    app: jaeger
spec:
  rules:
  - host: jaeger.example.com # Modify this to your desired hostname
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jaeger
            port:
              number: 16686
