clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /var/lib/promtail/positions.yml

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: "docker"
          __path__: "/var/lib/docker/containers/*/*.log"

  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: "syslog"
          __path__: "/var/log/*"
